---
- hosts: 44.193.211.43   
  become: true
  tasks:
   - name: copy war file to server
     copy:
              src: /var/lib/jenkins/workspace/ansible pipeline/webapp/target/webapp.war
              dest: /opt/apache-tomcat-9.0.60/rrr
...     
